linux: &linux
  os: linux
  sudo: required
  language: python

env:
  global:
    - CONAN_CLANG_VERSIONS=4.0
    - CONAN_ARCHS=x86_64
    - CONAN_BUILD_TYPES=Release

matrix:
  include:
    - <<: *linux
      python: 2.7
    - <<: *linux
      python: 3.6

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
